// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSKZHZetBCFrMCVj79H8HoXm6Lg0JWtTM',
    appId: '1:666821658855:web:c46676c50925027bfffa42',
    messagingSenderId: '666821658855',
    projectId: 'dev-access-472419-f1',
    authDomain: 'dev-access-472419-f1.firebaseapp.com',
    storageBucket: 'dev-access-472419-f1.firebasestorage.app',
    measurementId: 'G-SCEJ83TTJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYK7yOxwZvg2zYuxkK828a53kAy2Fg0Fk',
    appId: '1:666821658855:android:217955b90bb11b28fffa42',
    messagingSenderId: '666821658855',
    projectId: 'dev-access-472419-f1',
    storageBucket: 'dev-access-472419-f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiRrTbgUqAM_w7iLdPnxYCKoAoTxKnIJs',
    appId: '1:666821658855:ios:3bafa58c7f0502aafffa42',
    messagingSenderId: '666821658855',
    projectId: 'dev-access-472419-f1',
    storageBucket: 'dev-access-472419-f1.firebasestorage.app',
    androidClientId: '666821658855-4bco9gtsuh8s3nd34nonh1luvcaj8hh4.apps.googleusercontent.com',
    iosClientId: '666821658855-cud819st7l4v0il5h4ngl1sg9o0mgqq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ladCourier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiRrTbgUqAM_w7iLdPnxYCKoAoTxKnIJs',
    appId: '1:666821658855:ios:3bafa58c7f0502aafffa42',
    messagingSenderId: '666821658855',
    projectId: 'dev-access-472419-f1',
    storageBucket: 'dev-access-472419-f1.firebasestorage.app',
    androidClientId: '666821658855-4bco9gtsuh8s3nd34nonh1luvcaj8hh4.apps.googleusercontent.com',
    iosClientId: '666821658855-cud819st7l4v0il5h4ngl1sg9o0mgqq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ladCourier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSKZHZetBCFrMCVj79H8HoXm6Lg0JWtTM',
    appId: '1:666821658855:web:aa485b576c418a58fffa42',
    messagingSenderId: '666821658855',
    projectId: 'dev-access-472419-f1',
    authDomain: 'dev-access-472419-f1.firebaseapp.com',
    storageBucket: 'dev-access-472419-f1.firebasestorage.app',
    measurementId: 'G-L8QEQGRKNE',
  );
}
